#!/bin/bash
# Enable SSL for o3app.ma (wildcard)
# Usage: sudo bash deployment/nginx/enable-ssl.sh
# Prerequisites: certbot DNS challenge completed for *.o3app.ma
set -e

DOMAIN="o3app.ma"
CERT="/etc/letsencrypt/live/$DOMAIN/fullchain.pem"
KEY="/etc/letsencrypt/live/$DOMAIN/privkey.pem"
CONF="/etc/nginx/sites-available/o3app.conf"
APP_DIR="/var/www/O3_app"

# ── 1. Get certificate if not exists ──
if [ ! -f "$CERT" ]; then
    echo "==> Getting SSL certificate (DNS challenge)..."
    echo ""
    echo "You will need to add a TXT record at your DNS provider:"
    echo "  _acme-challenge.o3app.ma"
    echo ""
    certbot certonly --manual --preferred-challenges dns \
        -d "$DOMAIN" -d "*.$DOMAIN"
fi

# ── 2. Verify cert exists ──
if [ ! -f "$CERT" ]; then
    echo "ERROR: Certificate not found at $CERT"
    echo "Run certbot manually first, then re-run this script."
    exit 1
fi

echo "==> Certificate found at $CERT"

# ── 3. Write full SSL Nginx config ──
echo "==> Writing SSL Nginx config..."

cat > "$CONF" << 'NGINX'
# O3 App — Nginx (o3app.ma) — SSL enabled
# Generated by deployment/nginx/enable-ssl.sh

# ── Upstream for Reverb WebSocket server ──
upstream reverb {
    server 127.0.0.1:8080;
}

# ── HTTP → HTTPS redirect (all domains) ──
server {
    listen 80;
    server_name o3app.ma *.o3app.ma;
    return 301 https://$host$request_uri;
}

# ── 1) shop.*.o3app.ma → Vue SPA (O3_ecom) — HTTPS ──
server {
    listen 443 ssl http2;
    server_name ~^shop\.(?<tenant>.+)\.o3app\.ma$;

    ssl_certificate     /etc/letsencrypt/live/o3app.ma/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/o3app.ma/privkey.pem;
    ssl_protocols       TLSv1.2 TLSv1.3;
    ssl_ciphers         HIGH:!aNULL:!MD5;

    root /var/www/O3_ecom/dist;
    index index.html;

    location /storage/ {
        proxy_pass https://$tenant.o3app.ma;
        proxy_set_header Host $tenant.o3app.ma;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }

    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff2?|ttf|eot)$ {
        expires 30d;
        add_header Cache-Control "public, immutable";
        try_files $uri =404;
    }

    location ~ /\. { deny all; }
}

# ── 2) o3app.ma + *.o3app.ma → Laravel — HTTPS ──
# Use regex so shop regex block (listed first) takes priority over this one
server {
    listen 443 ssl http2;
    server_name o3app.ma ~^(?!shop\.)([a-z0-9-]+\.)?o3app\.ma$;

    ssl_certificate     /etc/letsencrypt/live/o3app.ma/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/o3app.ma/privkey.pem;
    ssl_protocols       TLSv1.2 TLSv1.3;
    ssl_ciphers         HIGH:!aNULL:!MD5;

    root /var/www/O3_app/public;
    index index.php;
    charset utf-8;
    client_max_body_size 20M;

    # ── WebSocket proxy for Laravel Reverb (wss://) ──
    location /app {
        proxy_pass             http://reverb;
        proxy_http_version     1.1;
        proxy_set_header       Upgrade $http_upgrade;
        proxy_set_header       Connection "upgrade";
        proxy_set_header       Host $host;
        proxy_set_header       X-Real-IP $remote_addr;
        proxy_set_header       X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header       X-Forwarded-Proto $scheme;
        proxy_read_timeout     60s;
        proxy_send_timeout     60s;
    }

    # ── Broadcasting auth endpoint ──
    location /broadcasting/auth {
        try_files $uri /index.php?$query_string;
    }

    # Force /storage/ requests through Laravel (tenant file serving)
    location /storage/ {
        try_files /dev/null /index.php?$query_string;
    }

    # Long timeout for product import
    location ~ /central/tenants/.*/import-products {
        fastcgi_pass unix:/run/php/php8.3-fpm.sock;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        include fastcgi_params;
        fastcgi_read_timeout 600s;
    }

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        fastcgi_pass unix:/run/php/php8.3-fpm.sock;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        include fastcgi_params;
    }

    location ~ /\.(?!well-known) { deny all; }
}
NGINX

# ── 4. Update .env for HTTPS ──
echo "==> Updating .env for HTTPS..."
cd "$APP_DIR"
sed -i 's|^APP_URL=.*|APP_URL=https://o3app.ma|' .env
sed -i 's|^VITE_REVERB_SCHEME=.*|VITE_REVERB_SCHEME=https|' .env
sed -i 's|^VITE_REVERB_PORT=.*|VITE_REVERB_PORT=443|' .env
sed -i 's|^REVERB_SCHEME=.*|REVERB_SCHEME=https|' .env

# ── 5. Rebuild frontend with HTTPS env ──
echo "==> Rebuilding frontend for HTTPS..."
npm run build

# ── 6. Test and reload Nginx ──
echo "==> Testing Nginx config..."
nginx -t

echo "==> Reloading Nginx..."
systemctl reload nginx

# ── 7. Setup auto-renewal cron ──
if ! crontab -l 2>/dev/null | grep -q certbot; then
    (crontab -l 2>/dev/null; echo "0 3 * * * certbot renew --quiet --post-hook 'systemctl reload nginx'") | crontab -
    echo "==> Auto-renewal cron added"
fi

echo ""
echo "========================================="
echo "  SSL enabled for $DOMAIN"
echo "========================================="
echo "  https://o3app.ma"
echo "  https://*.o3app.ma"
echo "  https://shop.*.o3app.ma"
echo "  wss://TENANT.o3app.ma/app/KEY"
echo "========================================="
